### ISSUE TITLE
[Question] Read-Host++ 

### ISSUE THREAD

**Issue by dfinke** [ShaunLawrie/PwshSpectreConsole#43]
Like ChatGPT Web.

Is there a way, with the PS functions here or in Spectre to create an inputbox, keep it at the bottom, type text, press enter and the inputbox remains there at the bottom ready for more. Then, after enter, the text request is handled and the results are displayed in a "listbox" above?

Like ChatGPT Web.

**Comment by ShaunLawrie** [comment]
Not with vanilla spectre.console, the built-in prompts can't be embedded in other widgets as far as I can tell.

With a bit of powershell + spectre console layouts & live rendering you can write your own input handler and manually set the text inside a widget to simulate a text entry. Example below.

This actually came out better than expected...
https://gist.github.com/ShaunLawrie/2ed8c580d685598e6faaea60e18d96ea

https://github.com/user-attachments/assets/860d06ae-063c-498f-89ad-62988c2edbed

There is a [spectre.console tui framework](https://github.com/patriksvensson/spectre.tui) in the works to support more dynamic terminal applications using the spectre console widgets which I think will handle this better but it's early stages.

**Comment by ShaunLawrie** [comment]
I think to do the listbox stuff better I need to find a way to expose the height of the widgets because you'd want to measure the size of the layout where the chat messages are and only show the ones that can fit. I just did a trivial check in that demo but it's assuming every response would be one line which isn't correct.
![image](https://github.com/user-attachments/assets/6d60cacc-5d80-4a5d-9c94-ea2ba8ee4374)

I'll keep pondering on this. In the meantime that gist should get you pretty far for a PoC using a real AI agent.

What will make things next-level is getting the code syntax highlighting and markdown stuff working but that's going to be a tough one 😅

**Comment by dfinke** [comment]
You read my mind!

- code syntax highlighting
- chart rendering
- markdown rendering

Thank you, cool stuff!
