### ISSUE TITLE
Is there a changelog of new features and breaking changes anywhere when upgrading to 2.1.1-prerelease018?

### ISSUE THREAD

**Issue by futuremotiondev** [ShaunLawrie/PwshSpectreConsole#44]
I rely on this library a lot, just wondering if there are any breaking changes, or if any cmdlets or functions have changed so I can properly update my scripts that use this module.

Thanks for any help!

**Comment by ShaunLawrie** [comment]
Hey @futuremotiondev,

The plan is that nothing should functionally break/stop working going to v2 but some rendering might look a little different. I went with a major version upgrade because I consider the visual changes "breaking".

The whole list of changes is here https://prerelease.pwshspectreconsole.com/guides/upgrading-to-2-0/

If you want to try out the prerelease version before the upgrade goes out the instructions are on that page.

If you have any issues with the new version reach out 🤙

**Comment by ShaunLawrie** [comment]
The upgrade doc is now at https://pwshspectreconsole.com/guides/upgrading-to-v2/
